name: sos_store_management
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  mime: ^1.0.0
  file_picker: ^5.0.0
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_functions: ^5.0.2
  crypto: ^3.0.0
  firebase_messaging: ^15.0.2
  form_field_validator: ^1.1.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  native_assets_cli: ^0.4.2
  image_picker: ^0.8.5+3
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  bdd_widget_test: ^1.2.1
  build_runner: ^2.4.9
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    # Uncomment the following lines if you have image assets
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
  #fonts:
    #- family: Poppins
      #fonts:
        #- asset: assets/fonts/Poppins-BlackItalic.ttf
         # style: italic
        #- asset: assets/fonts/Poppins-Black.ttf
